# Application Version
version: v0.0.5
# Application Look
per_page: 80                           # number of rows per page
short_date_format: "%T"                # this is for today's date
long_date_format: "%Y-%m-%d at %T"     # format of all other dates
human_readable_counter: true           # set to 'false' for exact counter
